
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was auto-generated from Translation.tt
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PinupMobile.Core.Strings
{
    [System.CodeDom.Compiler.GeneratedCode("Transation.tt", "1")]
    public class Translation
    {
        private static ILocalisation _stringLoader;

        public static ILocalisation StringLoader
        {
            get { return _stringLoader; }
            set { _stringLoader = value; }
        }


        /// <summary>
        /// Looks up any string in the translated resources.
        /// </summary>
        public static string Get(string key)
        {
            return StringLoader.GetString(key);
        }
    }
}

